[project]
name = "openwrt-cm5"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "attrs",
    "cattrs",
    "bcrypt",
    "pyyaml",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["test"]

[tool.ruff]
line-length = 100
output-format = 'grouped'

[tool.ruff.format]
quote-style = 'single'

[tool.ruff.lint]
select = ['B', 'E', 'F', 'I']
