theme: dark

http:
  address: 0.0.0.0:8080
  session_ttl: 720h

users:
  - name: admin
    password: $2b$10$FrKu0YMMRPnLjqVAB2eZaelhUKkXTqd/nrvg0O7jWfpF3BM69SRe. # "changeme" (bcrypt); change via web UI

dns:
  bind_hosts:
    - 0.0.0.0
    - 10.8.0.1
  port: 53
  # Upstream DNS will be set from VPN_DNS on first boot
  upstream_dns:
    - 1.1.1.1
    - 1.0.0.1
  bootstrap_dns:
    - 1.1.1.1
    - 1.0.0.1
  allowed_clients:
    - localhost
    - 10.8.0.0/24
  ratelimit: 20
  refuse_any: true
  enable_dnssec: false
  edns_client_subnet:
    enabled: false
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: false
  upstream_mode: fastest_addr

filtering:
  protection_enabled: true
  filtering_enabled: true
  blocked_response_ttl: 10
  parental_enabled: false
  safe_search:
    enabled: false
  rewrites: []
  blocked_services:
    schedule:
      time_zone: UTC
    ids: []

filters:
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_51.txt
    name: HaGeZi's Pro++ Blocklist
    id: 2
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_44.txt
    name: HaGeZi's Threat Intelligence Feeds
    id: 3
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt
    name: Dandelion Sprout's Anti-Malware List
    id: 4
  - enabled: true
    url: https://phishing.army/download/phishing_army_blocklist_extended.txt
    name: Phishing Army
    id: 1759330557
  - enabled: false
    url: https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_trackers.txt
    name: AdGuard CNAME Trackers
    id: 1759330558
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_61.txt
    name: HaGeZi's Samsung Tracker Blocklist
    id: 1759328878
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_63.txt
    name: HaGeZi's Windows/Office Tracker Blocklist
    id: 1759328879
  - enabled: false
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_6.txt
    name: Dandelion Sprout's Game Console Adblock List
    id: 1697906947
  - enabled: false
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt
    name: Perflyst and Dandelion Sprout's Smart-TV Blocklist
    id: 1697906949
  - enabled: true
    url: https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/MobileFilter/sections/specific_app.txt
    name: AdGuard Mobile Ads Filter
    id: 1759330559
  - enabled: true
    url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
    name: Android Tracking List
    id: 1759330560
  - enabled: false
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt
    name: NoCoin Filter List
    id: 1697906952
  - enabled: true
    url: https://nsfw.oisd.nl
    name: OISD NSFW
    id: 1697906958

whitelist_filters:
  - enabled: true
    url: https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
    name: anudeepND's whitelist
    id: 1697906960
  - enabled: true
    url: https://raw.githubusercontent.com/hl2guide/AdGuard-Home-Whitelist/main/whitelist.txt
    name: AdGuardTeam/AdGuardHome whitelist
    id: 1697906961
  - enabled: false
    url: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral.txt
    name: HaGeZi Referral Allowlist
    id: 1759330564

user_rules:
  - '@@||captive.apple.com^'
  - '@@||connectivitycheck.gstatic.com^'
  - '@@||clients3.google.com^'
  - '@@||nmcheck.gnome.org^'
  - '@@||detectportal.firefox.com^'
  - '@@||www.msftconnecttest.com^'
  - '@@||www.msftncsi.com^'

dhcp:
  enabled: false

clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []

log:
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: false

os:
  group: ""
  user: ""
  rlimit_nofile: 0

querylog:
  enabled: true
  file_enabled: true
  interval: 24h
  size_memory: 1000
  ignored: []

statistics:
  enabled: true
  interval: 24h
  ignored: []

schema_version: 28
